services:
  guides:
    image: inveracity/guides:latest
    container_name: guides
    build:
      context: .
      dockerfile: docker/guides.dockerfile

    ports:
      - "8080:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.ui.rule=Host(`christopherbaklid.com`)
      - traefik.http.routers.ui.entrypoints=websecure
      - traefik.http.routers.ui.tls.certresolver=myresolver
      - traefik.http.routers.ui.tls=true
    restart: "unless-stopped"
